"""Central configuration values for the AntaDrishti prototype."""

from pathlib import Path

PROJECT_NAME = "AntaDrishti"
APP_NAME = "ANTAHDRISHTI"
APP_DESCRIPTION = "AI-Powered Public Safety Intelligence System"
CAMERA_SOURCE = 0
YOLO_CONFIDENCE_THRESHOLD = 0.35
MAX_PROCESSING_FRAMES = 300
FALL_PERSISTENCE_SECONDS = 0.8
FALL_TRACK_TIMEOUT_SECONDS = 1.2
CROWD_COUNT_THRESHOLD = 5
CROWD_OCCUPANCY_THRESHOLD = 0.12
CROWD_HIGH_COUNT_THRESHOLD = 10
CROWD_HIGH_OCCUPANCY_THRESHOLD = 0.25
CROWD_CLEAR_SECONDS = 3.0
ALERT_COOLDOWN_SECONDS = 30.0
ALTERCATION_PROXIMITY_SCALE = 1.0
OPTICAL_FLOW_MAGNITUDE_THRESHOLD = 1.5
OPTICAL_FLOW_MOTION_FRACTION = 0.02
ALTERCATION_CONFIRM_HITS = 40
ALTERCATION_CONFIRM_FRAMES = ALTERCATION_CONFIRM_HITS
ALTERCATION_WINDOW_FRAMES = 48
ALTERCATION_MIN_MOTION_HITS = 6

BASE_DIR = Path(__file__).resolve().parent
DB_PATH = BASE_DIR / "database" / "alerts.db"
OUTPUT_DIR = BASE_DIR / "outputs"
SNAPSHOT_DIR = BASE_DIR / "snapshots"
SAMPLE_VIDEO_DIR = BASE_DIR / "sample_videos"
YOLO_MODEL_PATH = BASE_DIR / "yolov8n.pt"

COLORS = {
    "danger": "#ff4b4b",
    "warning": "#ffbf47",
    "success": "#21c354",
    "info": "#4da3ff",
}

SEVERITY_LEVELS = {
    "Low": (0, 3),
    "Medium": (4, 6),
    "High": (7, 10),
}
